---
title: "Frequentist anaylsis"
author: "Yiyang Shi"
date: "12/3/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Frequentist Penalty Selection of LASSO Logistic Regression
```{r}
set.seed(123)

data_cv10 <- vfold_cv(hotel_sub, v = 10)


# Logistic LASSO Regression Model Spec
logistic_lasso_spec_tune <- logistic_reg() %>%
    set_engine('glmnet') %>%
    set_args(mixture = 1, penalty = tune()) %>%
    set_mode('classification')

# Recipe
logistic_rec <- recipe(is_canceled ~ ., data = hotel_sub) %>%
    step_normalize(all_numeric_predictors()) %>% 
    step_dummy(all_nominal_predictors()) %>%  
    step_nzv(all_predictors()) %>% 
    step_corr(all_predictors()) %>% 
    step_mutate(is_canceled = factor(is_canceled))
    # factor more categorical variables later on


# Workflow (Recipe + Model)
log_lasso_wf <- workflow() %>% 
    add_recipe(logistic_rec) %>%
    add_model(logistic_lasso_spec_tune) 


# Tune Model
penalty_grid <- grid_regular(
  penalty(range = c(-5,1)), #log10 transformed  (kept moving min down from 0)
  levels = 30)

tune_output <- tune_grid( 
  log_lasso_wf,
  resamples = data_cv10,
  metrics = metric_set(roc_auc,accuracy),
  control = control_resamples(save_pred = TRUE, event_level = 'second'),
  grid = penalty_grid 
)

# Visualize Model Evaluation Metrics from Tuning
autoplot(tune_output) + theme_classic()
```

```{r}
best_se_penalty <- 
  select_by_one_std_err(tune_output, 
                        metric = 'roc_auc', 
                        desc(penalty)) 
# choose penalty value based on the largest penalty within 1 se of the highest CV roc_auc
best_se_penalty
```

```{r}
final_fit_se <- finalize_workflow(log_lasso_wf, best_se_penalty) %>% # incorporates penalty value to workflow 
    fit(data = hotel_sub)

final_fit_se %>% tidy()
```